apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-web.yaml
  - deployment-worker.yaml
  - job-migrate.yaml
  - service.yaml
  - ingress.yaml
