class AnalyticsService
  DEFAULT_REACTION_TOTALS = {
    total: 0, like: 0, readinglist: 0, unicorn: 0,
    exploding_head: 0, raised_hands: 0, fire: 0, unique_reactors: 0
  }.freeze

  # When a date range exceeds this many days the older portion is bucketed by
  # week instead of by day to keep payload size and chart point count bounded.
  # The most recent DAILY_HISTORY_DAYS still resolve daily.
  DAILY_HISTORY_DAYS = 180

  def initialize(user_or_org, start_date: "", end_date: "", article_id: nil)
    @user_or_org = user_or_org
    @article_id = article_id
    @start_date = Time.zone.parse(start_date.to_s)&.beginning_of_day
    @end_date = Time.zone.parse(end_date.to_s)&.end_of_day || Time.current.end_of_day

    # Clamp start_date to the owner's registration date so we don't generate
    # a long tail of empty zero buckets predating the account.
    @start_date = clamp_start_to_scope_floor(@start_date)

    load_data
  end

  # Computes total counts for comments, reactions, follows and page views
  def totals
    if (fast = totals_from_activities)
      return fast
    end

    {
      comments: { total: comment_data.size },
      follows: { total: follow_data.size },
      reactions: calculate_reactions_totals,
      page_views: calculate_page_views_totals
    }
  end

  # Computes counts for comments, reactions, follows and page views per each
  # day (or per week for data older than DAILY_HISTORY_DAYS).
  def grouped_by_day
    return {} unless start_date && end_date

    # The activities fast-path is itself the cache (single indexed lookup per
    # article_activities row), and we deliberately leave it uncached so worker
    # writes show up immediately. The raw-row fallback, however, runs whenever
    # any in-scope article is missing an ArticleActivity row (i.e. mid-backfill
    # for an owner with many articles), so we wrap *only* that branch in a
    # short-TTL cache to avoid hammering the DB on every reload while backfill
    # catches up. The TTL is short enough that newly-backfilled freshness still
    # arrives within ~one minute.
    fast = grouped_by_day_from_activities
    return fast if fast

    cache_key = [
      "analytics-grouped-by-day-raw-v1",
      user_or_org.class.name, user_or_org.id,
      start_date, end_date, article_id
    ].join("-")
    Rails.cache.fetch(cache_key, expires_in: 1.minute) { grouped_by_day_from_raw }
  end

  # Returns the list of referrers
  def referrers(top: 20)
    if (fast = referrers_from_activities(top: top))
      return fast
    end

    # count_all is the name of the field autogenerated by Rails with COUNT(*)
    counts = page_view_data
      .group(:domain)
      .order(Arel.sql("sum_counts_for_number_of_views DESC"))
      .limit(top)
      .sum("counts_for_number_of_views")
    # we transform this in a list of hashes in case we need to add more keys
    domains = counts.map { |domain, count| { domain: domain, count: count } }

    { domains: domains }
  end

  # Returns top contributors who engaged with the user/org's articles
  # via reactions (excl. bookmarks) and comments, excluding self-interactions.
  # Comments are weighted 6x, reactions 1x.
  def top_contributors(limit: 20)
    return [] unless article_data.exists?

    # Use subqueries to avoid loading all IDs into memory for large datasets
    article_ids_subquery = article_data.select(:id)

    # Determine author IDs to exclude self-interactions
    author_ids = article_data.distinct.pluck(:user_id)

    # Reactions (excl readinglist/self) → weight 1
    reactions_sql = Reaction.for_analytics
      .where(reactable_id: article_ids_subquery, reactable_type: "Article")
      .where.not(category: "readinglist")
      .where.not(user_id: author_ids)
    reactions_sql = reactions_sql.where(created_at: start_date..end_date) if start_date && end_date
    reactions_query = reactions_sql
      .select("user_id, COUNT(*) AS reactions_count, 0 AS comments_count, COUNT(*) AS score")
      .group(:user_id)

    # Comments (excl self, score > 0) → weight 6
    # Comments carry more weight than reactions because they require
    # significantly more effort and drive meaningful discussion.
    comments_sql = Comment
      .where(commentable_id: article_ids_subquery, commentable_type: "Article")
      .where("score > 0")
      .where.not(user_id: author_ids)
    comments_sql = comments_sql.where(created_at: start_date..end_date) if start_date && end_date
    comments_query = comments_sql
      .select("user_id, 0 AS reactions_count, COUNT(*) AS comments_count, COUNT(*) * 6 AS score")
      .group(:user_id)

    # UNION and aggregate
    union_sql = "(" \
      "#{reactions_query.to_sql}" \
      " UNION ALL " \
      "#{comments_query.to_sql}" \
    ")"

    rows = ActiveRecord::Base.connection.select_all(
      "SELECT user_id, SUM(reactions_count)::int AS reactions_count, " \
      "SUM(comments_count)::int AS comments_count, SUM(score)::int AS score " \
      "FROM #{union_sql} AS combined " \
      "GROUP BY user_id ORDER BY score DESC, user_id ASC LIMIT #{limit.to_i}",
    )

    user_ids = rows.map { |r| r["user_id"] }
    users_by_id = User.where(id: user_ids).index_by(&:id)

    rows.filter_map do |row|
      user = users_by_id[row["user_id"]]
      next unless user

      {
        user_id: user.id,
        username: user.username,
        name: user.name,
        profile_image: user.profile_image_90,
        reactions_count: row["reactions_count"],
        comments_count: row["comments_count"],
        score: row["score"]
      }
    end
  end

  # Returns what percentage of followers engaged (reacted or commented)
  # with the user/org's articles in the given period.
  def follower_engagement
    follower_scope = Follow
      .where(followable_type: user_or_org.class.name, followable_id: user_or_org.id)
      .where(blocked: false)

    total_followers = follower_scope.count
    return { total_followers: 0, engaged_followers: 0, ratio: 0.0 } if total_followers.zero?
    return { total_followers: total_followers, engaged_followers: 0, ratio: 0.0 } unless article_data.exists?

    follower_ids_subquery = follower_scope.select(:follower_id)
    article_ids_subquery = article_data.select(:id)

    # Followers who reacted (excl readinglist)
    reacting_scope = Reaction.for_analytics
      .where(reactable_id: article_ids_subquery, reactable_type: "Article")
      .where.not(category: "readinglist")
      .where(user_id: follower_ids_subquery)
    reacting_scope = reacting_scope.where(created_at: start_date..end_date) if start_date && end_date

    # Followers who commented (score > 0)
    commenting_scope = Comment
      .where(commentable_id: article_ids_subquery, commentable_type: "Article")
      .where("score > 0")
      .where(user_id: follower_ids_subquery)
    commenting_scope = commenting_scope.where(created_at: start_date..end_date) if start_date && end_date

    engaged_count = ActiveRecord::Base.connection.select_value(
      "SELECT COUNT(DISTINCT user_id) FROM (" \
      "#{reacting_scope.select(:user_id).to_sql} UNION ALL #{commenting_scope.select(:user_id).to_sql}" \
      ") AS engaged",
    ).to_i

    {
      total_followers: total_followers,
      engaged_followers: engaged_count,
      ratio: (engaged_count.to_f / total_followers * 100).round(1)
    }
  end

  private

  attr_reader(
    :user_or_org, :article_id, :start_date, :end_date,
    :article_data, :reaction_data, :comment_data, :follow_data, :page_view_data
  )

  def load_data
    @article_data = Article.published.from_subforem.where("#{user_or_org.class.name.downcase}_id" => user_or_org.id)
    if @article_id
      @article_data = @article_data.where(id: @article_id)

      # check article_id is published and belongs to the user/org
      raise ArgumentError, I18n.t("services.analytics_service.no_stats") unless @article_data.exists?

      article_ids = [@article_id]
    else
      article_ids = @article_data.ids
    end

    # prepare relations for metrics
    @comment_data = Comment
      .where(commentable_id: article_ids, commentable_type: "Article")
      .where("score > 0")
    @follow_data = Follow
      .where(followable_type: user_or_org.class.name, followable_id: user_or_org.id)
    @reaction_data = Reaction.for_analytics
      .where(reactable_id: article_ids, reactable_type: "Article")
    @page_view_data = PageView.where(article_id: article_ids)

    # filter data by date if needed
    return unless start_date && end_date

    @comment_data = @comment_data.where(created_at: @start_date..@end_date)
    @reaction_data = @reaction_data.where(created_at: @start_date..@end_date)
    @page_view_data = @page_view_data.where(created_at: @start_date..@end_date)
  end

  def calculate_reactions_totals
    # NOTE: the order of the keys needs to be the same as the one of the counts
    keys = %i[total like readinglist unicorn exploding_head raised_hands fire unique_reactors]
    counts = reaction_data.pick(
      Arel.sql("COUNT(*)"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'like')"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'readinglist')"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'unicorn')"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'exploding_head')"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'raised_hands')"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'fire')"),
      Arel.sql("COUNT(DISTINCT user_id)"),
    )

    if counts
      # this transforms the counts, eg. [1, 0, 1, 0, ...]
      # in a hash, eg. {total: 1, like: 0, readinglist: 1, unicorn: 0, ...}
      keys.zip(counts).to_h
    else
      DEFAULT_REACTION_TOTALS
    end
  end

  def calculate_page_views_totals
    total_views = article_data.sum(:page_views_count)
    logged_in_page_view_data = page_view_data.where.not(user_id: nil)
    average = logged_in_page_view_data.pick(Arel.sql("AVG(time_tracked_in_seconds)"))
    average_read_time_in_seconds = (average || 0).round # average is a BigDecimal

    {
      total: total_views,
      average_read_time_in_seconds: average_read_time_in_seconds,
      total_read_time_in_seconds: average_read_time_in_seconds * total_views
    }
  end

  def calculate_comments_stats_per_day(comment_data)
    # AR returns a hash with date => count, we transform it using ISO dates for convenience
    comment_data.group(bucket_sql).count.transform_keys(&:iso8601)
  end

  def calculate_follows_stats_per_day(follow_data)
    # AR returns a hash with date => count, we transform it using ISO dates for convenience
    follow_data.group(bucket_sql).count.transform_keys(&:iso8601)
  end

  def calculate_reactions_stats_per_day(reaction_data)
    # we issue one single query that contains all requested aggregates
    # and that groups them by date
    reactions = reaction_data.select(
      Arel.sql(bucket_sql).as("date"),
      Arel.sql("COUNT(*)").as("total"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'like')").as("like"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'readinglist')").as("readinglist"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'unicorn')").as("unicorn"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'exploding_head')").as("exploding_head"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'raised_hands')").as("raised_hands"),
      Arel.sql("COUNT(*) FILTER (WHERE category = 'fire')").as("fire"),
      Arel.sql("COUNT(DISTINCT user_id)").as("unique_reactors"),
    ).group(bucket_sql)

    # this transforms the collection of pseudo Reaction objects previously selected
    # in a hash with all reaction category counts plus unique reactors
    reactions.each_with_object({}) do |reaction, hash|
      hash[reaction.date.iso8601] = {
        total: reaction.total,
        like: reaction.like,
        readinglist: reaction.readinglist,
        unicorn: reaction.unicorn,
        exploding_head: reaction.exploding_head,
        raised_hands: reaction.raised_hands,
        fire: reaction.fire,
        unique_reactors: reaction.unique_reactors
      }
    end
  end

  def calculate_page_views_stats_per_day(page_view_data)
    # we issue one single query that contains all requested aggregates
    # and that groups them by date
    page_views = page_view_data.select(
      Arel.sql(bucket_sql).as("date"),
      Arel.sql("SUM(counts_for_number_of_views)").as("total"),
      # count the average only for logged in users
      Arel.sql("AVG(time_tracked_in_seconds) FILTER (WHERE user_id IS NOT NULL)").as("average"),
    ).group(bucket_sql)

    # this transforms the collection of pseudo PageView objects previously selected
    # in a hash, eg. {total: 2, average_read_time_in_seconds: 10, total_read_time_in_seconds: 20}
    page_views.each_with_object({}) do |page_view, hash|
      average = (page_view.average || 0).round # average is a BigDecimal
      hash[page_view.date.iso8601] = {
        total: page_view.total,
        average_read_time_in_seconds: average,
        total_read_time_in_seconds: page_view.total * average
      }
    end
  end

  def stats_per_day(date, comments_stats:, follows_stats:, reactions_stats:, page_views_stats:)
    # we need these defaults because SQL doesn't return any data for dates that don't have any
    default_reactions_stats = {
      total: 0, like: 0, readinglist: 0, unicorn: 0,
      exploding_head: 0, raised_hands: 0, fire: 0, unique_reactors: 0
    }
    default_page_views_stats = { total: 0, average_read_time_in_seconds: 0, total_read_time_in_seconds: 0 }
    iso_date = date.iso8601

    {
      comments: { total: comments_stats[iso_date] || 0 },
      follows: { total: follows_stats[iso_date] || 0 },
      reactions: reactions_stats[iso_date] || default_reactions_stats,
      page_views: page_views_stats[iso_date] || default_page_views_stats
    }
  end

  # Original raw-row computation path. Always works; serves as fallback when
  # the article_activities cache table doesn't yet cover all articles in scope.
  def grouped_by_day_from_raw
    comments_stats_per_day = calculate_comments_stats_per_day(comment_data)
    follows_stats_per_day = calculate_follows_stats_per_day(follow_data)
    reactions_stats_per_day = calculate_reactions_stats_per_day(reaction_data)
    page_views_stats_per_day = calculate_page_views_stats_per_day(page_view_data)

    stats = {}
    bucket_dates.each do |date|
      stats[date.iso8601] = stats_per_day(
        date,
        comments_stats: comments_stats_per_day,
        follows_stats: follows_stats_per_day,
        reactions_stats: reactions_stats_per_day,
        page_views_stats: page_views_stats_per_day,
      )
    end
    stats
  end

  # Fast-path: serve grouped_by_day from the per-article ArticleActivity cache
  # rows. Returns nil (and triggers backfill) if any in-scope article does not
  # yet have an activity row, so the caller falls back to the raw query path.
  #
  # When @article_id is set this is a per-article check (single row); spec
  # explicitly: "single article stats should use the activity table if it's
  # available but fall back to the current system if it isn't".
  def grouped_by_day_from_activities
    activities = scoped_activities
    return nil if activities.nil?

    # Aggregate raw counters across articles (storage shape, not response shape)
    # so we can correctly derive bucket-level averages.
    pv_raw = aggregate_page_view_counters(activities)
    rx_raw = aggregate_reaction_counters(activities)
    cm_raw = aggregate_comment_counters(activities)

    follows_stats_per_day = calculate_follows_stats_per_day(follow_data)

    stats = {}
    bucket_dates.each do |date|
      iso = date.iso8601
      bucket_iso_dates = bucket_iso_keys(date)
      stats[iso] = {
        comments: { total: bucket_iso_dates.sum { |d| cm_raw[d].to_i } },
        follows: { total: follows_stats_per_day[iso] || 0 },
        reactions: sum_reaction_bucket(rx_raw, bucket_iso_dates),
        page_views: sum_page_view_bucket(pv_raw, bucket_iso_dates)
      }
    end
    stats
  end

  # Returns a totals hash matching #totals using only article_activity rows.
  # Returns nil if the cache doesn't yet cover all in-scope articles.
  def totals_from_activities
    activities = scoped_activities
    return nil if activities.nil?

    pv = aggregate_page_view_counters(activities)
    rx = aggregate_reaction_counters(activities)
    cm = aggregate_comment_counters(activities)
    pv_iso_dates = pv.keys
    rx_iso_dates = rx.keys
    cm_iso_dates = cm.keys

    {
      comments: { total: cm_iso_dates.sum { |d| cm[d].to_i } },
      follows: { total: follow_data.size },
      reactions: sum_reaction_bucket(rx, rx_iso_dates),
      page_views: sum_page_view_bucket(pv, pv_iso_dates)
    }
  end

  # Returns referrers in the same shape as #referrers using activity rows.
  def referrers_from_activities(top: 20)
    activities = scoped_activities
    return nil if activities.nil?

    counts = Hash.new(0)
    activities.each do |a|
      a.daily_referrers.each do |iso, day_hash|
        next unless iso_in_range?(iso)

        day_hash.each { |domain, n| counts[domain] += n.to_i }
      end
    end
    domains = counts.sort_by { |_, n| -n }.first(top).map { |d, n| { domain: d, count: n } }
    { domains: domains }
  end

  # Loads the ArticleActivity rows for the request scope, or returns nil and
  # enqueues lazy backfill jobs if any are missing. Result is memoized so the
  # totals/referrers/grouped_by_day fast paths share one DB load.
  def scoped_activities
    return @scoped_activities if defined?(@scoped_activities)

    article_ids = article_data.ids
    if article_ids.empty?
      @scoped_activities = nil
      return nil
    end

    activities = ArticleActivity.where(article_id: article_ids).index_by(&:article_id)
    missing = article_ids - activities.keys
    if missing.any?
      # Enqueue a single batch backfill rather than one job per article so
      # that owners with thousands of articles don't spike the queue on a
      # cold dashboard load. The current request still falls back to the
      # raw-table path; the cache is warm on the next visit.
      Articles::BackfillActivitiesWorker.perform_async(missing)
      @scoped_activities = nil
      return nil
    end

    @scoped_activities = activities.values
  end

  def iso_in_range?(iso)
    return true unless start_date && end_date

    d = Date.iso8601(iso)
    d >= start_date.to_date && d <= end_date.to_date
  rescue ArgumentError
    false
  end

  # Aggregates the raw counter shape stored in daily_page_views across all
  # in-scope articles, returning {iso => {total, sum_read_seconds, logged_in_count}}.
  def aggregate_page_view_counters(activities)
    out = Hash.new { |h, k| h[k] = { "total" => 0, "sum_read_seconds" => 0, "logged_in_count" => 0 } }
    activities.each do |a|
      a.daily_page_views.each do |iso, raw|
        next unless iso_in_range?(iso)

        out[iso]["total"] += raw["total"].to_i
        out[iso]["sum_read_seconds"] += raw["sum_read_seconds"].to_i
        out[iso]["logged_in_count"] += raw["logged_in_count"].to_i
      end
    end
    out
  end

  def aggregate_reaction_counters(activities)
    out = Hash.new do |h, k|
      h[k] = { "total" => 0, "like" => 0, "readinglist" => 0, "unicorn" => 0,
               "exploding_head" => 0, "raised_hands" => 0, "fire" => 0,
               "reactor_ids" => [] }
    end
    activities.each do |a|
      a.daily_reactions.each do |iso, raw|
        next unless iso_in_range?(iso)

        ArticleActivity::REACTION_CATEGORIES.each { |c| out[iso][c] += raw[c].to_i }
        out[iso]["total"] += raw["total"].to_i
        out[iso]["reactor_ids"].concat(Array(raw["reactor_ids"]))
      end
    end
    out
  end

  def aggregate_comment_counters(activities)
    out = Hash.new(0)
    activities.each do |a|
      a.daily_comments.each do |iso, n|
        next unless iso_in_range?(iso)

        out[iso] += n.to_i
      end
    end
    out
  end

  # Returns the list of ISO date strings that contribute to a given bucket
  # start date. For daily buckets that's just [date]; for weekly buckets it's
  # the seven days starting at the bucket's Monday clamped to the request range.
  def bucket_iso_keys(bucket_start)
    return [bucket_start.iso8601] unless weekly_bucketing?

    cutoff = (end_date - DAILY_HISTORY_DAYS.days).to_date
    if bucket_start < cutoff
      window_end = [bucket_start + 6, cutoff - 1, end_date.to_date].min
      window_start = [bucket_start, start_date.to_date].max
      (window_start..window_end).map(&:iso8601)
    else
      [bucket_start.iso8601]
    end
  end

  def sum_reaction_bucket(rx, iso_dates)
    base = { total: 0, like: 0, readinglist: 0, unicorn: 0,
             exploding_head: 0, raised_hands: 0, fire: 0, unique_reactors: 0 }
    reactor_set = Set.new
    iso_dates.each do |d|
      sub = rx[d]
      next if sub.nil? || (sub.respond_to?(:empty?) && sub.empty?)

      base[:total] += sub["total"].to_i
      ArticleActivity::REACTION_CATEGORIES.each { |c| base[c.to_sym] += sub[c].to_i }
      Array(sub["reactor_ids"]).each { |uid| reactor_set << uid }
    end
    base[:unique_reactors] = reactor_set.size
    base
  end

  def sum_page_view_bucket(pv, iso_dates)
    total = 0
    sum_read = 0
    logged_count = 0
    iso_dates.each do |d|
      sub = pv[d]
      next if sub.nil? || sub.empty?

      total += sub["total"].to_i
      sum_read += sub["sum_read_seconds"].to_i
      logged_count += sub["logged_in_count"].to_i
    end
    average = logged_count.positive? ? (sum_read.to_f / logged_count).round : 0
    { total: total, average_read_time_in_seconds: average, total_read_time_in_seconds: total * average }
  end

  # Returns the timestamp the owner became part of the platform.
  # Users have a dedicated registered_at column; organizations fall back to created_at.
  def owner_registered_at
    if user_or_org.respond_to?(:registered_at) && user_or_org.registered_at
      user_or_org.registered_at
    else
      user_or_org.created_at
    end
  end

  # Clamps the requested start to the earliest meaningful date for this scope:
  #
  # - For owner-wide stats (no article_id): the owner's registration / org
  #   creation date. Earlier dates would just produce a long tail of empty
  #   zero buckets predating the account.
  # - For per-article stats (article_id present): the article's publication
  #   date. The owner-registration floor is wrong here because an article may
  #   live in an organization that was created long after the article was
  #   published (cross-posted into a newer org), and clamping to the org's
  #   creation date silently hides every bit of activity from before the org
  #   existed. An article's stats should reflect the article's own lifetime.
  def clamp_start_to_scope_floor(parsed_start)
    return parsed_start unless parsed_start

    floor = scope_floor_at&.beginning_of_day
    floor && parsed_start < floor ? floor : parsed_start
  end

  def scope_floor_at
    return article_published_at if article_id && article_published_at

    owner_registered_at
  end

  def article_published_at
    return @article_published_at if defined?(@article_published_at)

    @article_published_at = Article.where(id: article_id).pick(:published_at)
  end

  # SQL expression used to bucket created_at into either a daily date or the
  # Monday of its ISO week, depending on whether the timestamp falls within
  # the most recent DAILY_HISTORY_DAYS of the requested range. Postgres returns
  # a date in either branch so AR transforms the result with `&:iso8601`.
  def bucket_sql
    if weekly_bucketing?
      cutoff = end_date - DAILY_HISTORY_DAYS.days
      cutoff_literal = ActiveRecord::Base.connection.quote(cutoff)
      "CASE WHEN created_at >= #{cutoff_literal} " \
        "THEN DATE(created_at) " \
        "ELSE DATE_TRUNC('week', created_at)::date END"
    else
      "DATE(created_at)"
    end
  end

  def weekly_bucketing?
    return false unless start_date && end_date

    (end_date - start_date) > DAILY_HISTORY_DAYS.days
  end

  # Iterates the set of bucket start dates that should appear in the response.
  # For weekly_bucketing? mode: weekly Mondays from start to cutoff, then daily
  # from cutoff to end_date. Otherwise: every day in range.
  def bucket_dates
    dates = []
    if weekly_bucketing?
      cutoff_date = (end_date - DAILY_HISTORY_DAYS.days).to_date
      week = start_date.to_date.beginning_of_week
      while week < cutoff_date
        dates << week
        week += 7
      end
      daily_start = [cutoff_date, start_date.to_date].max
      dates.concat((daily_start..end_date.to_date).to_a)
    else
      dates.concat((start_date.to_date..end_date.to_date).to_a)
    end
    dates
  end
end
