version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: false
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-10
  brakeman:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-6"
    exclude_patterns:
      - "app/javascript/**/index.js" # exclude barrel files
  duplication:
    enabled: true
    config:
      count_threshold: 3
exclude_patterns:
  - "**/*.test.js"
  - "**/*.test.jsx"
  - "**/.eslintrc.js"
  - "**/__stories__/"
  - "**/__tests__/"
  - "*.js"
  - "app/assets/javascripts/lib/"
  - "bin/"
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "lib/tasks/"
  - "node_modules/"
  - "script/"
  - "spec/"
  - "test/"
  - "tests/"
  - "vendor/"
