ignore:
  - "vendor"
  - "bin"
  - "**/*.svg"
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
