version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg13
    restart: unless-stopped

    environment:
      POSTGRES_DB: forem_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - forem-postgres:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d forem_production
      interval: 10s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7.0-alpine
    restart: unless-stopped

    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}

    volumes:
      - forem-redis:/data

    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli -a "$${REDIS_PASSWORD}" ping | grep PONG
      interval: 10s
      timeout: 5s
      retries: 10

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}


  web:
    build:
      context: .
      dockerfile: Containerfile
      target: production

    restart: unless-stopped

    command:
      - sleep
      - infinity

    environment:
      RAILS_ENV: production
      NODE_ENV: production

      APP_DOMAIN: ${APP_DOMAIN}
      APP_PROTOCOL: ${APP_PROTOCOL}
      COMMUNITY_NAME: ${COMMUNITY_NAME}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      SESSION_KEY: ${SESSION_KEY}

      DATABASE_URL: ${DATABASE_URL}

      REDIS_URL: ${REDIS_URL}
      REDIS_SIDEKIQ_URL: ${REDIS_SIDEKIQ_URL}
      REDIS_SESSIONS_URL: ${REDIS_SESSIONS_URL}
      REDIS_RPUSH_URL: ${REDIS_RPUSH_URL}

      FOREM_OWNER_SECRET: ${FOREM_OWNER_SECRET}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

    volumes:
      - forem-uploads:/opt/apps/forem/public/uploads

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    expose:
      - "3000"


  sidekiq:
    build:
      context: .
      dockerfile: Containerfile
      target: production

    restart: unless-stopped

    command:
      - sleep
      - infinity

    environment:
      RAILS_ENV: production
      NODE_ENV: production

      APP_DOMAIN: ${APP_DOMAIN}
      APP_PROTOCOL: ${APP_PROTOCOL}
      COMMUNITY_NAME: ${COMMUNITY_NAME}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      SESSION_KEY: ${SESSION_KEY}

      DATABASE_URL: ${DATABASE_URL}

      REDIS_URL: ${REDIS_URL}
      REDIS_SIDEKIQ_URL: ${REDIS_SIDEKIQ_URL}
      REDIS_SESSIONS_URL: ${REDIS_SESSIONS_URL}
      REDIS_RPUSH_URL: ${REDIS_RPUSH_URL}

      FOREM_OWNER_SECRET: ${FOREM_OWNER_SECRET}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

    volumes:
      - forem-uploads:/opt/apps/forem/public/uploads

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  forem-postgres:
  forem-redis:
  forem-uploads:
