json.type_of              "classified_listing"
json.id                   listing.id
json.title                listing.title
json.slug                 listing.slug
json.body_markdown        listing.body_markdown
json.tag_list             listing.cached_tag_list
json.tags                 listing.tag_list
json.category             listing.category
json.processed_html       listing.processed_html
json.published            listing.published
