import { h, Fragment } from 'preact';
import { useState, useEffect } from 'preact/hooks';
import PropTypes from 'prop-types';
import { Modal, ButtonNew as Button } from '@crayons';

const OPTIONS = [
  {
    value: 'no_ai',
    title: 'No AI',
    description: 'Written entirely by a human without meaningful assistance from AI generation tools.',
    badge: 'Hand Written',
  },
  {
    value: 'some_ai',
    title: 'Some AI (AI-assisted)',
    description: 'Written by a human with assistance from AI tools (e.g. rough draft, code generation, major edits, translations).',
    badge: 'Assisted',
  },
  {
    value: 'fully_autonomous',
    title: 'Fully Autonomous',
    description: 'Entirely generated by an autonomous AI system or agent with little to no human editing.',
    badge: 'AI Generated',
  },
];

export const AiDisclosureModal = ({
  currentValue = 'not_disclosed',
  isOpen,
  onClose,
  onChange,
}) => {
  const [selected, setSelected] = useState(currentValue || 'not_disclosed');

  useEffect(() => {
    setSelected(currentValue || 'not_disclosed');
  }, [currentValue]);

  const handleSelect = (val) => {
    setSelected(val);
    if (typeof onChange === 'function') {
      onChange({
        preventDefault: () => {},
        stopPropagation: () => {},
        target: {
          name: 'aiDisclosureLevel',
          value: val,
        },
      });
    }
  };

  const handleClear = () => {
    setSelected('not_disclosed');
    if (typeof onChange === 'function') {
      onChange({
        preventDefault: () => {},
        stopPropagation: () => {},
        target: {
          name: 'aiDisclosureLevel',
          value: 'not_disclosed',
        },
      });
    }
  };

  const handleSave = () => {
    onClose();
  };

  if (!isOpen) return null;

  return (
    <Modal
      title="AI Tooling Usage Disclosure"
      onClose={onClose}
      backdropDismissible
      size="medium"
    >
      <div className="p-4">
        <p className="fs-base color-base-70 mb-4">
          Disclose the extent to which artificial intelligence tools were used to research, write, or generate this post.
        </p>

        <div className="flex flex-col gap-3">
          {OPTIONS.map((opt) => {
            const isSelected = selected === opt.value;
            return (
              <div
                key={opt.value}
                onClick={() => handleSelect(opt.value)}
                role="radio"
                aria-checked={isSelected}
                tabIndex={0}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    handleSelect(opt.value);
                  }
                }}
                className={`p-3 radius-default border cursor-pointer transition-all flex items-start gap-3 ${
                  isSelected
                    ? 'border-accent-brand bg-base-subtle shadow-sm ring-1 ring-accent-brand'
                    : 'border-base-20 hover:border-base-40 bg-base'
                }`}
              >
                <input
                  type="radio"
                  id={`ai_disclosure_opt_${opt.value}`}
                  name="aiDisclosureLevelRadio"
                  value={opt.value}
                  checked={isSelected}
                  onChange={() => handleSelect(opt.value)}
                  className="mt-1 crayons-radio cursor-pointer"
                  onClick={(e) => e.stopPropagation()}
                />
                <div className="flex-1">
                  <div className="flex items-center justify-between gap-2 mb-1">
                    <label
                      htmlFor={`ai_disclosure_opt_${opt.value}`}
                      className="fs-base fw-bold cursor-pointer m-0"
                    >
                      {opt.title}
                    </label>
                    <span
                      className="fs-xs px-2 py-0.5 radius-default bg-base-20 color-base-70 fw-medium shrink-0 text-center inline-flex items-center justify-center"
                      style={{ width: '100px' }}
                    >
                      {opt.badge}
                    </span>
                  </div>
                  <p className="fs-s color-base-60 m-0 leading-normal">
                    {opt.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
      <div className="flex justify-between items-center gap-2 p-4 border-t border-base-20">
        <div>
          {selected && selected !== 'not_disclosed' && (
            <Button variant="ghost" onClick={handleClear}>
              Clear selection
            </Button>
          )}
        </div>
        <Button variant="primary" onClick={handleSave}>
          Done
        </Button>
      </div>
    </Modal>
  );
};

AiDisclosureModal.propTypes = {
  currentValue: PropTypes.string,
  isOpen: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired,
  onChange: PropTypes.func.isRequired,
};

AiDisclosureModal.displayName = 'AiDisclosureModal';
