# See AbExperiment namespace for details of goals and variants
#
################################################################################
################################################################################
#
# Checklist for creating a new feed experiment:
#
# - [ ] Create and/or reference the forem/forem issue with desired configuration
# - [ ] Identify the winner for the past experiment by adding the `winner:
#       <variant-name>` attribute to the past experiment.
# - [ ] Set the past experiments `ended_at` to the new experiments started_at.
# - [ ] Copy the previous experiment and prepend and rename to
#       `feed_strategy_starting_CCYYMMDD`
# - [ ] Update the `started_at` to `CCYY-MM-DD`
# - [ ] Assign the variants; the winner of the previous experiment SHOULD be in
#       this array.
# - [ ] Remove the winner attribute from the newly copied
#       `feed_strategy_starting_CCYYMMDD`
# - [ ] Assign weights and make the corresponding
#       `./config/feed-variants/*.json` files where * is the new named variants.
# - [ ] Each newly named variant should have a description; typically briefly
#       explaining the difference between it and the winner of the last experiment.
# - [ ] Run `bin/rspec spec/services/articles/feeds/variant_query_spec.rb` to
#       verify each newly added variant's SQL
# - [ ] Submit a pull request and ping the Forem Core (in Slack) for a review.
#
################################################################################
################################################################################

experiments:
  personalized_email_digests_ab_test:
    started_at: 2026-05-19
    variants:
    - legacy
    - personalized
    weights:
    - 50
    - 50
    goals:
    - user_clicks_email_link
  feed_strategy_starting_20240805:
    started_at: 2024-08-05
    variants:
    - 20240701-variant-c
    - 20240805-variant-a
    - 20240805-variant-b
    - 20240805-variant-c
    weights:
    - 70
    - 10
    - 10
    - 10
    goals:
    - user_creates_pageview
    - user_creates_article_reaction
    - user_views_pages_on_at_least_two_different_days_within_a_week
    - user_views_pages_on_at_least_four_different_days_within_a_week
  active_discussion_ordering_07_03:
    started_at: 2024-07-03
    ended_at: 2024-07-18
    winner: last_comment_plus_comment_score_capped_50
    variants:
    - base
    - last_comment_plus_comment_score_capped_25
    - last_comment_plus_comment_score_capped_50
    - last_comment_plus_comment_score_capped_80
    - last_comment_plus_comment_score_capped_120
    weights:
    - 60
    - 12
    - 12
    - 8
    - 8
    goals:
    - user_creates_pageview
    - user_creates_article_reaction
    - user_creates_comment
    - user_views_pages_on_at_least_two_different_days_within_a_week
    - user_views_pages_on_at_least_four_different_days_within_a_week
  feed_strategy_starting_20240701:
    started_at: 2024-07-01
    ended_at: 2024-08-05
    winner: 20240701-variant-c
    variants:
    - 20240616-variant-b
    - 20240701-variant-a
    - 20240701-variant-b
    - 20240701-variant-c
    weights:
    - 70
    - 10
    - 10
    - 10
    goals:
    - user_creates_pageview
    - user_creates_article_reaction
    - user_views_pages_on_at_least_two_different_days_within_a_week
    - user_views_pages_on_at_least_four_different_days_within_a_week
  digest_article_ordering_06_25:
    started_at: 2024-06-25
    ended_at: 2024-07-18
    winner: base
    variants:
    - base
    - more_comment_score
    - much_more_comment_score
    - much_much_more_comment_score
    weights:
    - 70
    - 10
    - 10
    - 10
    goals:
    - user_creates_email_feed_event
    - user_creates_comment
    - user_views_pages_on_at_least_two_different_days_within_a_week
    - user_views_pages_on_at_least_four_different_days_within_a_week
cache: true
precision: 2
cookies: false
