require "rails_helper"

RSpec.describe Concepts::AnchorGenerator do
  let(:concept) { build(:concept, description: nil, anchor_embedding: nil) }
  let(:generator) { described_class.new(concept) }
  let(:ai_client) { instance_double(Ai::Base) }
  let(:embedding_client) { instance_double(Ai::Embedding) }
  let(:mock_embedding) { Array.new(768, 0.1) }

  before do
    allow(Ai::Base).to receive(:new).and_return(ai_client)
    allow(Ai::Embedding).to receive(:new).and_return(embedding_client)
    allow(embedding_client).to receive(:call).and_return(mock_embedding)
  end

  context "when description is blank" do
    before do
      allow(ai_client).to receive(:call).and_return("Synthetic description generated by Gemini.")
    end

    it "generates description and embedding and saves concept" do
      generator.call
      expect(concept.description).to eq("Synthetic description generated by Gemini.")
      expect(concept.anchor_embedding.to_a).to eq(mock_embedding)
      expect(concept).to be_persisted
    end
  end

  context "when description is already present" do
    let(:concept) { build(:concept, description: "Pre-existing description.", anchor_embedding: nil) }

    it "does not call Gemini for description, but generates embedding and saves" do
      expect(ai_client).not_to receive(:call)
      generator.call
      expect(concept.description).to eq("Pre-existing description.")
      expect(concept.anchor_embedding.to_a).to eq(mock_embedding)
      expect(concept).to be_persisted
    end
  end
end
