class ChangeIntegerPksToBigint < ActiveRecord::Migration[5.1]
  def up
    # PKs
    change_column :ahoy_messages, :id, :bigint
    change_column :articles, :id, :bigint
    change_column :blocks, :id, :bigint
    change_column :broadcasts, :id, :bigint
    change_column :collections, :id, :bigint
    change_column :comments, :id, :bigint
    change_column :delayed_jobs, :id, :bigint
    change_column :github_issues, :id, :bigint
    change_column :identities, :id, :bigint
    change_column :mentions, :id, :bigint
    change_column :notes, :id, :bigint
    change_column :notifications, :id, :bigint
    change_column :organizations, :id, :bigint
    change_column :podcast_episodes, :id, :bigint
    change_column :podcasts, :id, :bigint
    change_column :reactions, :id, :bigint
    change_column :roles, :id, :bigint
    change_column :taggings, :id, :bigint
    change_column :tags, :id, :bigint
    change_column :tweets, :id, :bigint
    change_column :users, :id, :bigint

    # reference columns
    change_column :ahoy_messages, :feedback_message_id, :bigint
    change_column :ahoy_messages, :user_id, :bigint
    change_column :api_secrets, :user_id, :bigint
    change_column :articles, :collection_id, :bigint
    change_column :articles, :job_opportunity_id, :bigint
    change_column :articles, :organization_id, :bigint
    change_column :articles, :second_user_id, :bigint
    change_column :articles, :third_user_id, :bigint
    change_column :articles, :user_id, :bigint
    change_column :badge_achievements, :rewarder_id, :bigint
    change_column :blocks, :user_id, :bigint
    change_column :buffer_updates, :article_id, :bigint
    change_column :buffer_updates, :tag_id, :bigint
    change_column :collections, :organization_id, :bigint
    change_column :collections, :user_id, :bigint
    change_column :comments, :commentable_id, :bigint
    change_column :comments, :user_id, :bigint
    change_column :display_ads, :organization_id, :bigint
    change_column :feedback_messages, :affected_id, :bigint
    change_column :feedback_messages, :offender_id, :bigint
    change_column :feedback_messages, :reporter_id, :bigint
    change_column :follows, :followable_id, :bigint
    change_column :follows, :follower_id, :bigint
    change_column :github_repos, :user_id, :bigint
    change_column :html_variant_successes, :article_id, :bigint
    change_column :html_variant_successes, :html_variant_id, :bigint
    change_column :html_variant_trials, :article_id, :bigint
    change_column :html_variant_trials, :html_variant_id, :bigint
    change_column :html_variants, :user_id, :bigint
    change_column :identities, :user_id, :bigint
    change_column :mentions, :mentionable_id, :bigint
    change_column :mentions, :user_id, :bigint
    change_column :mentor_relationships, :mentee_id, :bigint
    change_column :mentor_relationships, :mentor_id, :bigint
    change_column :notes, :author_id, :bigint
    change_column :notes, :noteable_id, :bigint
    change_column :notifications, :notifiable_id, :bigint
    change_column :notifications, :user_id, :bigint
    change_column :podcast_episodes, :podcast_id, :bigint
    change_column :reactions, :reactable_id, :bigint
    change_column :reactions, :user_id, :bigint
    change_column :roles, :resource_id, :bigint
    change_column :tag_adjustments, :article_id, :bigint
    change_column :tag_adjustments, :tag_id, :bigint
    change_column :tag_adjustments, :user_id, :bigint
    change_column :taggings, :tag_id, :bigint
    change_column :taggings, :taggable_id, :bigint
    change_column :taggings, :tagger_id, :bigint
    change_column :tweets, :user_id, :bigint
    change_column :users, :organization_id, :bigint
    change_column :users_roles, :role_id, :bigint
    change_column :users_roles, :user_id, :bigint
  end

  def down
    # PKs
    change_column :ahoy_messages, :id, :integer
    change_column :articles, :id, :integer
    change_column :blocks, :id, :integer
    change_column :broadcasts, :id, :integer
    change_column :collections, :id, :integer
    change_column :comments, :id, :integer
    change_column :delayed_jobs, :id, :integer
    change_column :github_issues, :id, :integer
    change_column :identities, :id, :integer
    change_column :mentions, :id, :integer
    change_column :notes, :id, :integer
    change_column :notifications, :id, :integer
    change_column :organizations, :id, :integer
    change_column :podcast_episodes, :id, :integer
    change_column :podcasts, :id, :integer
    change_column :reactions, :id, :integer
    change_column :roles, :id, :integer
    change_column :taggings, :id, :integer
    change_column :tags, :id, :integer
    change_column :tweets, :id, :integer
    change_column :users, :id, :integer

    # reference columns
    change_column :ahoy_messages, :feedback_message_id, :integer
    change_column :ahoy_messages, :user_id, :integer
    change_column :api_secrets, :user_id, :integer
    change_column :articles, :collection_id, :integer
    change_column :articles, :job_opportunity_id, :integer
    change_column :articles, :organization_id, :integer
    change_column :articles, :second_user_id, :integer
    change_column :articles, :third_user_id, :integer
    change_column :articles, :user_id, :integer
    change_column :badge_achievements, :rewarder_id, :integer
    change_column :blocks, :user_id, :integer
    change_column :buffer_updates, :article_id, :integer
    change_column :buffer_updates, :tag_id, :integer
    change_column :collections, :organization_id, :integer
    change_column :collections, :user_id, :integer
    change_column :comments, :commentable_id, :integer
    change_column :comments, :user_id, :integer
    change_column :display_ads, :organization_id, :integer
    change_column :feedback_messages, :affected_id, :integer
    change_column :feedback_messages, :offender_id, :integer
    change_column :feedback_messages, :reporter_id, :integer
    change_column :follows, :followable_id, :integer
    change_column :follows, :follower_id, :integer
    change_column :github_repos, :user_id, :integer
    change_column :html_variant_successes, :article_id, :integer
    change_column :html_variant_successes, :html_variant_id, :integer
    change_column :html_variant_trials, :article_id, :integer
    change_column :html_variant_trials, :html_variant_id, :integer
    change_column :html_variants, :user_id, :integer
    change_column :identities, :user_id, :integer
    change_column :mentions, :mentionable_id, :integer
    change_column :mentions, :user_id, :integer
    change_column :mentor_relationships, :mentee_id, :integer
    change_column :mentor_relationships, :mentor_id, :integer
    change_column :notes, :author_id, :integer
    change_column :notes, :noteable_id, :integer
    change_column :notifications, :notifiable_id, :integer
    change_column :notifications, :user_id, :integer
    change_column :podcast_episodes, :podcast_id, :integer
    change_column :reactions, :reactable_id, :integer
    change_column :reactions, :user_id, :integer
    change_column :roles, :resource_id, :integer
    change_column :taggings, :tag_id, :integer
    change_column :taggings, :taggable_id, :integer
    change_column :taggings, :tagger_id, :integer
    change_column :tweets, :user_id, :integer
    change_column :users, :organization_id, :integer
    change_column :users_roles, :role_id, :integer
    change_column :users_roles, :user_id, :integer
  end
end
