require "rails_helper"
require "swagger_helper"

# rubocop:disable RSpec/EmptyExampleGroup
# rubocop:disable RSpec/VariableName
# rubocop:disable Layout/LineLength

RSpec.describe "Api::V1::Docs::Users" do
  let(:Accept) { "application/vnd.forem.api-v1+json" }
  let(:api_secret) { create(:api_secret) }
  let(:user) { api_secret.user }

  let(:banned_user) { create(:user) }
  let(:article) { create(:article, user: banned_user, published: true) }
  let(:comment) { create(:comment, user: banned_user, article: article) }

  before do
    user.add_role(:admin)
  end

  describe "PUT /users/:id/suspend" do
    before do
      user.add_role(:admin)
    end

    path "/api/users/{id}/suspend" do
      put "Suspend a User" do
        tags "users"
        description "Suspend a user's account.

### Suspension Details:
- The user associated with the API key must have an `admin` or `moderator` role.
- Assigns the `suspended` role to the user, preventing them from posting new content (articles or comments) while suspended.
- Existing content is not deleted.
- Suspended users are not notified in the UI; if you want them to know, you must notify them explicitly."
        operationId "suspendUser"
        produces "application/json"
        parameter name: :id, in: :path, required: true,
                  description: "The unique ID of the user to suspend.",
                  schema: {
                    type: :integer,
                    format: :int32,
                    minimum: 1
                  },
                  example: 1

        response "204", "User successfully unpublished" do
          let(:"api-key") { api_secret.secret }
          let(:id) { banned_user.id }
          add_examples

          run_test!
        end

        response "401", "Unauthorized" do
          let(:regular_user) { create(:user) }
          let(:low_security_api_secret) { create(:api_secret, user: regular_user) }
          let(:"api-key") { low_security_api_secret.secret }
          let(:id) { banned_user.id }
          add_examples

          run_test!
        end

        response "404", "Unknown User ID" do
          let(:"api-key") { api_secret.secret }
          let(:id) { 10_000 }
          add_examples

          run_test!
        end
      end
    end
  end

  describe "PUT /users/:id/limited" do
    before do
      user.add_role(:admin)
    end

    path "/api/users/{id}/limited" do
      put "Add limited role for a User" do
        tags "users"
        description "Limit a user's account permissions.

### Limited Details:
- Requires `admin` or `moderator` privileges.
- Assigns the `limited` role, which rate-limits notifications generated by their actions (such as publishing new posts or comments).
- Does not restrict content creation or delete content."
        operationId "limitUser"
        produces "application/json"
        parameter name: :id, in: :path, required: true,
                  description: "The ID of the user to limit.",
                  schema: {
                    type: :integer,
                    format: :int32,
                    minimum: 1
                  },
                  example: 1

        response "204", "User successfully limited" do
          let(:"api-key") { api_secret.secret }
          let(:id) { banned_user.id }
          add_examples

          run_test!
        end

        response "401", "Unauthorized" do
          let(:regular_user) { create(:user) }
          let(:low_security_api_secret) { create(:api_secret, user: regular_user) }
          let(:"api-key") { low_security_api_secret.secret }
          let(:id) { banned_user.id }
          add_examples

          run_test!
        end

        response "404", "Unknown User ID" do
          let(:"api-key") { api_secret.secret }
          let(:id) { 10_000 }
          add_examples

          run_test!
        end
      end
    end
  end

  describe "DELETE /users/:id/limited" do
    before do
      user.add_role(:admin)
    end

    path "/api/users/{id}/limited" do
      delete "Remove limited for a User" do
        tags "users"
        description "Remove the limited role, restoring the user to general privileges. Requires `admin` or `moderator` role."
        operationId "unLimitUser"
        produces "application/json"
        parameter name: :id, in: :path, required: true,
                  description: "The ID of the user to un-limit.",
                  schema: {
                    type: :integer,
                    format: :int32,
                    minimum: 1
                  },
                  example: 1

        response "204", "User successfully un-limited" do
          let(:"api-key") { api_secret.secret }
          let(:id) { banned_user.id }
          add_examples

          run_test!
        end

        response "401", "Unauthorized" do
          let(:regular_user) { create(:user) }
          let(:low_security_api_secret) { create(:api_secret, user: regular_user) }
          let(:"api-key") { low_security_api_secret.secret }
          let(:id) { banned_user.id }
          add_examples

          run_test!
        end

        response "404", "Unknown User ID" do
          let(:"api-key") { api_secret.secret }
          let(:id) { 10_000 }
          add_examples

          run_test!
        end
      end
    end

    describe "PUT /users/:id/spam" do
      before do
        user.add_role(:admin)
      end

      path "/api/users/{id}/spam" do
        put "Add spam role for a User" do
          tags "users"
          description "Flag a user as spammer.

### Spam Role Details:
- Requires `admin` or `moderator` privileges.
- Stops the user from creating new posts or comments, acting as a shadowban or block on activity.
- Existing content remains but is hidden from search/feeds."
          operationId "spamUser"
          produces "application/json"
          parameter name: :id, in: :path, required: true,
                    description: "The ID of the user to assign the spam role.",
                    schema: {
                      type: :integer,
                      format: :int32,
                      minimum: 1
                    },
                    example: 1

          response "204", "Spam role assigned to the user successfully" do
            let(:"api-key") { api_secret.secret }
            let(:id) { banned_user.id }
            add_examples

            run_test!
          end

          response "401", "Unauthorized" do
            let(:regular_user) { create(:user) }
            let(:low_security_api_secret) { create(:api_secret, user: regular_user) }
            let(:"api-key") { low_security_api_secret.secret }
            let(:id) { banned_user.id }
            add_examples

            run_test!
          end

          response "404", "Unknown User ID" do
            let(:"api-key") { api_secret.secret }
            let(:id) { 10_000 }
            add_examples

            run_test!
          end
        end
      end
    end

    describe "DELETE /users/:id/spam" do
      before do
        user.add_role(:admin)
      end

      path "/api/users/{id}/spam" do
        delete "Remove spam role from a User" do
          tags "users"
          description "Unflag a user as spammer, restoring general permissions. Requires `admin` or `moderator` role."
          operationId "unSpamUser"
          produces "application/json"
          parameter name: :id, in: :path, required: true,
                    description: "The ID of the user to remove the spam role from.",
                    schema: {
                      type: :integer,
                      format: :int32,
                      minimum: 1
                    },
                    example: 1

          response "204", "Successfully removed the spam role from a user" do
            let(:"api-key") { api_secret.secret }
            let(:id) { banned_user.id }
            add_examples

            run_test!
          end

          response "401", "Unauthorized" do
            let(:regular_user) { create(:user) }
            let(:low_security_api_secret) { create(:api_secret, user: regular_user) }
            let(:"api-key") { low_security_api_secret.secret }
            let(:id) { banned_user.id }
            add_examples

            run_test!
          end

          response "404", "Unknown User ID" do
            let(:"api-key") { api_secret.secret }
            let(:id) { 10_000 }
            add_examples

            run_test!
          end
        end
      end
    end

    describe "PUT /users/:id/trusted" do
      before do
        user.add_role(:admin)
      end

      path "/api/users/{id}/trusted" do
        put "Add trusted role for a User" do
          tags "users"
          description "Assign the trusted role to a user.

### Trusted Role Details:
- Requires `admin` or `moderator` privileges.
- Trusted users gain privileges like casting flag votes on inappropriate content or participating in priority review queues.
- Triggers a system notification and an email to the user."
          operationId "trustUser"
          produces "application/json"
          parameter name: :id, in: :path, required: true,
                    description: "The ID of the user to assign the trusted role.",
                    schema: {
                      type: :integer,
                      format: :int32,
                      minimum: 1
                    },
                    example: 1

          response "204", "Trusted role assigned to the user successfully" do
            let(:"api-key") { api_secret.secret }
            let(:id) { user.id }
            add_examples

            run_test!
          end

          response "401", "Unauthorized" do
            let(:regular_user) { create(:user) }
            let(:low_security_api_secret) { create(:api_secret, user: regular_user) }
            let(:"api-key") { low_security_api_secret.secret }
            let(:id) { user.id }
            add_examples

            run_test!
          end

          response "404", "Unknown User ID" do
            let(:"api-key") { api_secret.secret }
            let(:id) { 10_000 }
            add_examples

            run_test!
          end
        end
      end
    end

    describe "DELETE /users/:id/trusted" do
      before do
        user.add_role(:admin)
      end

      path "/api/users/{id}/trusted" do
        delete "Remove trusted role from a User" do
          tags "users"
          description "Revoke the trusted role, returning the user to general status. Requires `admin` or `moderator` role."
          operationId "unTrustUser"
          produces "application/json"
          parameter name: :id, in: :path, required: true,
                    description: "The ID of the user to remove the trusted role from.",
                    schema: {
                      type: :integer,
                      format: :int32,
                      minimum: 1
                    },
                    example: 1

          response "204", "Successfully removed the trusted role from a user" do
            let(:"api-key") { api_secret.secret }
            let(:id) { user.id }
            add_examples

            run_test!
          end

          response "401", "Unauthorized" do
            let(:regular_user) { create(:user) }
            let(:low_security_api_secret) { create(:api_secret, user: regular_user) }
            let(:"api-key") { low_security_api_secret.secret }
            let(:id) { user.id }
            add_examples

            run_test!
          end

          response "404", "Unknown User ID" do
            let(:"api-key") { api_secret.secret }
            let(:id) { 10_000 }
            add_examples

            run_test!
          end
        end
      end
    end
  end
end
# rubocop:enable RSpec/VariableName
# rubocop:enable RSpec/EmptyExampleGroup
