# frozen_string_literal: true

source "https://rubygems.org"
ruby "2.7.0"

gem "activerecord", "~> 5.2.3" # Databases on Rails
gem "yard", "~> 0.9.19" # YARD is a documentation generation tool for the Ruby programming language
gem "yard-activerecord", "~> 0.0.16" # YARD extension that handles and interprets methods used when developing applications with ActiveRecord
gem "yard-activesupport-concern", "~> 0.0.1" # YARD extension that brings support for modules making use of ActiveSupport::Concern
